# Generated by Django 3.0.6 on 2020-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'NR - NOT RATED'), (1, 'G - GENERAL AUDIENCES'), (2, 'PG - PARENTAL GUIDANCE'), (3, 'R - RESTRICTED')], default=0),
        ),
    ]
